name: master workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploys
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy recipe in AWS server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PEM_KEY }}
          port: ${{ secrets.PRODUCTION_PORT }}
          script: |
            cd ~/poap-fun
            docker system prune -f
            git pull origin master
            make deploy COMPOSE_ENV=production
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: New production release at https://poap.fun/
          SLACK_USERNAME: cd-bot
